# COGS 118A - Project Checkpoint

# Names

Hopefully your team is at least this good. Obviously you should replace these with your names.

- Luke Skerrett
- Joshua Salce
- Justin Ubamudu
- Luke Mitbo

# Abstract 
This section should be short and clearly stated. It should be a single paragraph <200 words.  It should summarize: 
- what your goal/problem is
- what the data used represents and how they are measured
- what you will be doing with the data
- how performance/success will be measured

# Background

Fill in the background and discuss the kind of prior work that has gone on in this research area here. **Use inline citation** to specify which references support which statements.  You can do that through HTML footnotes (demonstrated here). I used to reccommend Markdown footnotes (google is your friend) because they are simpler but recently I have had some problems with them working for me whereas HTML ones always work so far. So use the method that works for you, but do use inline citations.

Here is an example of inline citation. After government genocide in the 20th century, real birds were replaced with surveillance drones designed to look just like birds<a name="lorenz"></a>[<sup>[1]</sup>](#lorenznote). Use a minimum of 2 or 3 citations, but we prefer more <a name="admonish"></a>[<sup>[2]</sup>](#admonishnote). You need enough citations to fully explain and back up important facts. 

Remeber you are trying to explain why someone would want to answer your question or why your hypothesis is in the form that you've stated.

# Problem Statement

Clearly describe the problem that you are solving. Avoid ambiguous words. The problem described should be well defined and should have at least one ML-relevant potential solution. Additionally, describe the problem thoroughly such that it is clear that the problem is quantifiable (the problem can be expressed in mathematical or logical terms), measurable (the problem can be measured by some metric and clearly observed), and replicable (the problem can be reproduced and occurs more than once).

# Data

We will be using several different datasets, including  arbitration salaries and player statistics from 2011-2022 for training, as well as 2022 player statistics to predict arbitration salaries for the 2023 season. We will then compare our predictions with the agreed 2023 arbitration salaries for all players we predict on.

## Dataset 1
* Name: MLB-Arbitration 2018-23.xls
* Link: https://docs.google.com/spreadsheets/d/1qxfZP9F05K7mIO4Kwv5D6hEbvtmAutIc807GSfoCQ1A/edit#gid=55083470
* Number of Observations (Total): 1261
* Number of Variables: 11-12
* Each observation consists of player data, including the player's name, service time (numerical "category"), season, team (category), position (category), previous year salary, current year salary, salaries offered by the player and team during arbitration (most blank due to no arbitration hearing), as well as an estimate of salary arrived at by the keepers of this data through a propreitary algorithm


## Dataset 1a (Group-Collected)
* Name: collected_arb_data.xlsx
* Link: https://github.com/COGS118A/Group029-SP23/blob/main/Data/collected_arb_data.xlsx
* Number of Observations (Total): 1358
* Number of Variables: 8
* Because of the lack of readily available data, we had to scrape several links from the website mlbtraderumors.com to create datasets very similar to Dataset 1 (a few variables excluded). All links scraped are as follows:
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2016/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2015/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2014/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2013/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2012/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2011/
  * https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2010/
* Each observation consists of player data, including the player's name, service time (numerical "category"), season, team (category), position (category), current year salary, salaries offered by the player and team during arbitration (most blank due to no arbitration hearing), as well as the midpoint between player and team salary requests.

## Dataset 2
* Name: Fangraphs Major League Leaderboards
* Links
  * Position Players/Hitters: https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=0&type=c,4,6,7,23,8,9,10,11,34,35,36,41,50,51,52,65,102,103,104,105,106,107,110,305,306,311,308,39,21,22,201&season=2022&month=0&season1=2010&ind=1&team=0&rost=0&age=0&filter=&players=0&startdate=&enddate=
  
  * Pitchers: https://www.fangraphs.com/leaders.aspx?pos=all&stats=pit&lg=all&qual=0&type=c,7,8,13,43,6,45,113,217,40,331,328,36,37,39,40,66,122,41,42,51,105,106,107,108,109,110,111&season=2022&month=0&season1=2010&ind=1&team=0&rost=0&age=0&filter=&players=0&startdate=&enddate=

  * Defensive Stats (Hitters and Pitchers): https://www.fangraphs.com/leaders.aspx?pos=all&stats=fld&lg=all&qual=0&type=c,6,9,28,39,61,59,17,18&season=2022&month=0&season1=2010&ind=1&team=0&rost=0&age=0&filter=&players=0&startdate=&enddate=
* Each observation contains in-game statistics for position players (offense and defense) as well as pitchers, though both categories will contain different variables. We try to include a lot of variables intitally to measure the full scope of a player's performance, such as a hitter's baserunning, hitting, and fielding ability, or a pitcher's ability to throw strikes, limit walks, get favorable outcomes on balls in play, etc. A "first-pass" feature selection has been performed by filtering our initial set of variables from all possible variables. More feature selection via EDA and other methods will be covered in our "Preliminary Results" section.

* Some important variables:
  * Position Players
    * PA (Discrete Number, how many times a player bats)
    * K%, BB% (% stats, what % PA a player strikes out/walks)
    * wOBA (rate stat of linear weights, the overall offenseive contribution per PA a player has to a game)
    * OPS (combined rate stat, a summation of two other rate stats that measure how well a player reaches base overall and how well a player can hit doubles, triples, or home runs)
    * O-Swing%, Z-Contact%, etc. (% stats, looks at % of pitches a player swings at outside zone, inside the zone, makes contact at pitches, etc.)
    * SB, CS (numbers, how many times a hitter on base steals a base or is thrown out trying to steal a base)
  * Pitchers
    * IP (Number, how many innings a pitcher throws, formatted as .1 for 1/3 inning, .2 for 2/3 inning)
    * ERA (Number, an estimator of pitcher performance by earned runs (9*(ER/IP))
    * K/9, BB/9, HR/9 (per 9 stats, takes discrete number stat and normalizes it per 9 innings)
    * O-Swing%, Z-Contact%, etc. (% stats, looks at % of pitches a pitcher cna get a hitter to swing at outside zone, inside the zone, makes contact at pitches, etc.)
  * Defense
    * E (numbers, how many "errors" on defense a player commits)
    * Inn (number, how many innings a player is on defense)
    * SB, CS (numbers, how many stolen bases allowed on defense and how many runners thrown out (applies to catchers only))
    * DRS (number, catch-all stat designed to measure how many runs a player can prevent through defense)

* Variables and Observations
  * Position Players/Hitters: 17592 x 34
  * Pitchers: 9707 x 30
  * Defensive Stats (Hitters and Pitchers): 27285 x 12



* Important: As with our arbitration data, position will need to be transformed to be one-hot encoded during pre-processing, as player salaries can vary greatly by position. Also, all numerical stats that will be inputs in our model will have to be scaled through sklearn StandardScaler() and MinMaxSclaer() objects, depending on the results of our EDA.
* __Important: The overwhelming majority of this data will be filtered out, as this includes data for ALL players, and not just arbitration-eligible players. Fangraphs has no mechanism to filter out by arbitration eligibility or service time.__

## Data Gathering

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests

%pip install unidecode
%pip install xlsx
import unidecode

Requirement already satisfied: unidecode in /Users/lukemitbo/anaconda3/envs/COGS118ASp23/lib/python3.9/site-packages (1.3.6)
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement xlsx (from versions: none)
ERROR: No matching distribution found for xlsx
Note: you may need to restart the kernel to use updated packages.

In [7]:
'''
Goal: Scrape all necessary MLBTradeRumors links to return arbitration data
      into a dataframe (data not readily/easily available)
--------------------------------------------------------------------------------
Inputs: link (string for website link)

Returns: N/A, but exports scraped data to csv, downloaded for additional data
         gathering performed outside code
'''
def scrape_mlbtr(link):
  # Making a GET request
  r = requests.get(link)
  
  # check status code for response received
  #print(r)
  
  # Parsing the HTML
  soup = BeautifulSoup(r.content, 'html.parser')

  # Scrapes the table linked in url
  s = soup.find('body', class_ = 'mlbtr').find('div', id = 'widget').find('div', id = 'widget_inner').find_all('table')
  df = pd.read_html(str(s))[0]

  # Names df according to the offseason, a.k.a. the year in the url + 1
  # e.g. 2016 data goes towards the 2017 offseason arbitration class
  df_name = 'mlbtr_arb' + str(int(link[-5:-1]) + 1) + '.csv'
  scraped_df = df.to_csv(df_name, index= True)

  # Saves to local runtime, would then download each csv and add additional data on position

# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2016/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2015/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2014/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2013/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2012/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2011/')
# scrape_mlbtr('https://transactions.mlbtraderumors.com/widget/arbitration-submissions/2010/')

In [10]:
# Importing scraped/collected data
arb11 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2011')
arb12 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2012')
arb13 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2013')
arb14 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2014')
arb15 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2015')
arb16 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2016')
arb17 = pd.read_excel('Data/collected_arb_data.xlsx', sheet_name ='arb2017')

# Importing found data
arb18 = pd.read_csv('Data/arb2018.csv')
arb19 = pd.read_csv('Data/arb2019.csv')
arb20 = pd.read_csv('Data/arb2020.csv')
arb22 = pd.read_csv('Data/arb2022.csv')
arb23 = pd.read_csv('Data/arb2023.csv')

# Importing Fangraphs Data
fg_hit = pd.read_csv('Data/HittingData.csv')
fg_pitch = pd.read_csv('Data/PitchingData.csv')
fg_def = pd.read_csv('Data/FieldingData.csv')

## Data Cleaning

We will deal with cleaning all of our data and merging them into four different DataFrames: 
* 2011-2022 position players arbitration + 2010-2021 performance statistics
* 2011-2022 pitchers arbitration + 2010-2021 performance statistics
* 2023 position players arbitration + 2022 performance statistics
* 2023 pitchers arbitration + 2022 performance statistics

We will introduce and use several helper functions to standardize variables such as names, position, as well as change necessary percentage columns from strings to floats. We then merge our datasets by player names (standardized) and season (of performance stats, not arbitration year). We include separate sections to handle our multi-year and 2023 datasets.

To summarize what is being standardized:
1. Player names: formatted to first + last, with special character phrases, accents, and non-letter characters removed 
2. Position: Keep first position, change all pitchers ending in 's' to starting pitchers (SP), the rest to relief pitcehrs (RP)
3. Service Time: keep the year only, as # of days do not count towards an arbitration salary
4. Salary: Convert all strings to ints, regardless if fully expressed in millions or '$x.xxMM' format

To summarize our procedure for cleaning:
1. Shift all imported data to beginning of player data
2. Add Prev. Season column that shifts year in arbitration data to previous year to match performance data used towards arbitration salary
3. Change some column names to be cleaner, standardize necessary variables to match Fangraphs data formats
4. Concat multiple years of data together, edit values to provide accurate merge between arbitration data and Fangraphs data, split by position players and pitchers
5. Observe and fix all missing values/errors (i.e. players with NaN data from missing the year due to injury or demotion, position players in pitchers dataset)

### Helper Functions

In [11]:
'''
Goal: Clean either found data or collected arbitration data
--------------------------------------------------------------------------------
Inputs: df (DataFrame of imported and read csv files)

Returns: df (DataFrame with cleaning done)
'''
def clean_data(df):
  # Set arbitration dataset year variable to the previous year
  prev_year = int(df.columns[0].split(' ')[1]) - 1

  # Convert first row into the column names 
  df.columns = df.iloc[0, :]

  # Return where the actual data starts (3rd row of Google Sheet)
  df = df.iloc[2:, :]

  # Rename columns of interest
  df.rename(columns = {df.columns[0]: 'Name' ,
                            df.columns[1]: 'Prev. Season', 
                            df.columns[3]: 'Position', 
                            df.columns[4]: 'Service Time', 
                            str(prev_year + 1) + ' Salary': 'Salary'}, inplace = True)

  # Filter out all players cut, demoted, or signed to extension
  df = df[df['Salary'].notnull() & df['Salary'].str.startswith("$")]
  
  #Add Season column, with the year set back one 
  #to indicate the year that affected the next year's arbitration salary
  df['Prev. Season'] = prev_year

  # Change Service time to the year
  df = df.astype({"Service Time": str})
  df["Service Time"] = df['Service Time'].apply(lambda x: x[0])

  df = df[['Name', 'Prev. Season', 'Position','Service Time','Salary']].reset_index(drop = True)

  # Changes all of Salary column values from strings to integers
  df['Salary'] = df['Salary'].apply(lambda x:  int(float(x.replace('$', '').replace('M', ''))*(10**6)) if x.__contains__('MM') else int(x.replace('$', '').replace(',','')))
  
  # Applies standardize_pos function to all values in Position column
  df["Position"] = df['Position'].apply(standard_position)

  # Applies standardize_names function to all values in Player column
  df['Name'] = df['Name'].apply(standard_name)

  #print(df.shape)
  return df

In [12]:
'''
Goal: Standardize names of strings to match the names of other datasets
--------------------------------------------------------------------------------
Inputs: inp_str (string representing name of MLB player)

Returns: The name reconstituted from its old format into a new one, 
removing accents and other special characters not found in other datasets
'''
def standard_name(inp_str):
  #print(inp_str)
  
  # Splits original name string and concatenates it in reverse order, with
  # unicode function applied
  if inp_str.__contains__(', '):
    name_li = inp_str.split(', ')
    out_str = unidecode.unidecode(name_li[1] + ' ' + name_li[0])
  else:
    out_str = unidecode.unidecode(inp_str)

  # Replace any special character phrases
  out_str = out_str.replace(' ,Adeg','').replace(' ,A+','')

  return out_str

In [13]:
'''
Goal: Standardize positions of players to develop discrete categories
  e.g. LHP-S is a left-handed starting pitcher, or SP
--------------------------------------------------------------------------------
Inputs: inp_str (string representing position of a given MLB player)

Returns: Player's position string reformatted to 
'''
def standard_position(inp_str):
  out_str = inp_str.upper()
  
  # Splits the formatting of old string into SP (starting pitcher) or RP (relief pitcher)
  if out_str.__contains__('LHP') or out_str.__contains__('RHP'):   
    if out_str[-1] == 'S':
      out_str = 'SP'
    else:
      out_str = 'RP'

  # Case of players who play multiple positions, which will have their
  # first listed position
  if out_str.__contains__('-'):
    # Special case of 'C-OF'
    if out_str[0] == 'C':
      out_str = out_str[0]
    else:   
      out_str = out_str[0:2]

  # position best matching INF of all other positions is 2B
  if out_str == 'INF':
    out_str = '2B'
  return out_str

In [14]:
'''
Goal: Convert all percentage statistics in Fangraphs datasets to floats
  e.g. '34.6%' is converted to 34.6 (float)
--------------------------------------------------------------------------------
Inputs: val (string the percentage statistic we want to convert)

Returns: new_per, converted % string into a float value 
'''
def remove_percentages(val):
  if type(val) != float and val.__contains__("%"):
    new_per = float(val[:-1])
    return new_per

In [15]:
'''
Goal: Convert all IP values that end with '.1' and '.2' to '
  .33' and '.67' respectively
  e.g. 123.2 (float) is converted to 123.67 (float)
--------------------------------------------------------------------------------
Inputs: val (float indicating IP for pitcher)

Returns: new_IP, converted from float to string, then back to float value 
'''
def change_IP(val):
  val = str(val)

  if val.endswith(".2"):
    # Change .2 IP to 2/3 IP
    
    new_IP = val.replace('.2','.67')
    return float(new_IP)
  elif  val.endswith(".1"):
    # Change .1 IP to 1/3 IP
    
    new_IP = val.replace('.1', '.33')
    return float(new_IP)
  else:
    return float(val)

### 2011-2022 Data (Training and Validation)

In [16]:
# Clean all data
arb11 = clean_data(arb11)
arb12 = clean_data(arb12)
arb13 = clean_data(arb13)
arb14 = clean_data(arb14)
arb15 = clean_data(arb15)
arb16 = clean_data(arb16)
arb17 = clean_data(arb17)
arb18 = clean_data(arb18)
arb19 = clean_data(arb19)
arb20 = clean_data(arb20)
arb22 = clean_data(arb22)

/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,
/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,

In [17]:
# Add together all "training" data of previous arbitration years
arb_dfs = [arb11, arb12, arb13, arb14, arb15, arb16, arb17, arb18, arb19, arb20, arb22]

df = pd.concat(arb_dfs, ignore_index=True)
print(df.shape)
df.head(10)

(1941, 5)

0               Name  Prev. Season Position Service Time   Salary
0         Adam Jones          2010       CF            3  3250000
1   Alberto Callaspo          2010       3B            3  2000000
2   Alberto Gonzalez          2010       2B            2   600000
3        Alex Gordon          2010       LF            3  1400000
4      Alexi Casilla          2010       SS            3   865000
5      Andres Torres          2010       CF            3  2100000
6   Andy Sonnanstine          2010       SP            3   912000
7        Angel Pagan          2010       OF            4  3500000
8     Anibal Sanchez          2010       SP            4  3700000
9  Armando Galarraga          2010       SP            2  2300000

In [18]:
#Splits large into dataframe containing PITCHERS ONLY
df_pitchers = df.loc[df['Position'].isin(['RP','SP'])].reset_index()

# Fix name differences for the join performed later
df_pitchers = df_pitchers.replace({'J.C. Ramirez':'JC Ramirez', 
                                   'Carl Edwards':'Carl Edwards Jr.', 
                                   'Wily * Peralta':'Wily Peralta', 
                                   'Kenyan Middleton':'Keynan Middleton', 
                                   'Matt Boyd':'Matthew Boyd', 
                                   'Vincent Velasquez':'Vince Velasquez',
                                   'Austin L. Adams':'Austin Adams',
                                   'Zach Britton':'Zack Britton',
                                   'Anthony DeSclafini': "Anthony DeSclafani",
                                   'A.J. Ramos': 'AJ Ramos',
                                   'Daniel Winkler': 'Dan Winkler',
                                   'Nate Eovaldi': 'Nathan Eovaldi',
                                   'Michael Dunn': 'Mike Dunn',
                                   'Robbie Ross': 'Robbie Ross Jr.',
                                   'Rubby De La Rosa': 'Rubby de la Rosa',
                                   'Michael Fiers': 'Mike Fiers',
                                   'Nate Karns': 'Nathan Karns'})

# Delete position players who pitched
df_pitchers = df_pitchers[~df_pitchers["Name"].isin(['Tony Wolters', 'Josh Phegley'])]

# Splits large df into dataframe containing POSITION PLAYERS ONLY
df_plyrs = df.loc[~df['Position'].isin(['RP','SP'])].reset_index()
# Fix name differences for the join performed later
df_plyrs = df_plyrs.replace({"Javy Baez" : "Javier Baez", 
                             "Delino DeShields Jr." : "Delino DeShields", 
                             "Albert Almora" : "Albert Almora Jr.", 
                             "Jacoby Jones" : "JaCoby Jones", 
                             "Giovanny Urshela" : "Gio Urshela", 
                             "Michael Taylor" : "Michael A. Taylor", 
                             "Vladimir Jr. Guerrero" : "Vladimir Guerrero Jr.", 
                             "Teoscar Hernández" : "Teoscar Hernandez", 
                             "Steven Souza": "Steven Souza Jr.",
                             'Nicholas Castellanos': 'Nick Castellanos',
                             'Jr. Melvin Upton': 'Melvin Upton Jr.',
                             'Mike Morse': 'Michael Morse',
                             'Alejandro de Aza': 'Alejandro De Aza',
                             'Eric Young': 'Eric Young Jr.',
                             'Dee Gordon': 'Dee Strange-Gordon',
                             "Travis D'Arnaud": "Travis d'Arnaud",
                             'D.J. LeMahieu': 'DJ LeMahieu',
                             'Ronnie Torreyes': 'Ronald Torreyes'})

In [19]:
#For all Fangraphs data, drop Fangraphs, MLB playerids and Teams
# Rename Season column to Prev. Season to be joined
fg_hit = fg_hit.drop(['playerid', 'Team','mlbamid'], axis=1)
fg_hit = fg_hit.rename(columns={'Season': 'Prev. Season'})

fg_pitch = fg_pitch.drop(['playerid', 'Team','mlbamid'], axis=1)
fg_pitch = fg_pitch.rename(columns={'Season': 'Prev. Season'})

fg_def = fg_def.drop(['playerid', 'Team','mlbamid','Pos'], axis=1)
fg_def = fg_def.rename(columns={'Season': 'Prev. Season'})

# Add metrics of players who played different positions in a single season
fg_def = fg_def.groupby(['Prev. Season','Name']).sum()

# Remove groupby into a pivot table, preserving order of columns
fg_def = fg_def.pivot_table(index=['Name','Prev. Season']).reset_index()[['Name','Prev. Season', 'Inn','E','DRS','UZR','RAA','FRM','SB','CS']]

# Standardize innings played on defense
fg_def['Inn'] = fg_def['Inn'].apply(change_IP)

In [22]:
fg_def

                 Name  Prev. Season     Inn  E  DRS  UZR  RAA  FRM   SB   CS
0         A.J. Achter          2014   11.00  0 -1.0  0.0  0.0 -0.2  1.0  0.0
1         A.J. Achter          2015   13.33  1 -1.0  0.0  0.0 -0.1  4.0  0.0
2         A.J. Achter          2016   37.67  0  0.0  0.0  0.0 -0.1  1.0  0.0
3          A.J. Alexy          2021   23.00  0  2.0  0.0  0.0  0.3  0.0  0.0
4          A.J. Alexy          2022    7.00  1 -1.0  0.0  0.0  0.1  0.0  0.0
...               ...           ...     ... ..  ...  ...  ...  ...  ...  ...
17448    Zeke Spruill          2013   11.33  0  0.0  0.0  0.0  0.1  0.0  0.0
17449    Zeke Spruill          2014   22.67  1 -1.0  0.0  0.0  0.2  1.0  0.0
17450  Zelous Wheeler          2014  152.67  2  2.0  0.8  0.0  0.0  0.0  0.0
17451   Zoilo Almonte          2013  239.00  0  0.0  2.2  0.0  0.0  0.0  0.0
17452   Zoilo Almonte          2014   77.67  0  0.0  1.4  0.0  0.0  0.0  0.0

[17453 rows x 10 columns]

#### Merging

In [24]:
# Merge arb data for pitchers with Fangraphs data
df_pitchers = pd.merge(df_pitchers, fg_pitch, on=['Name', 'Prev. Season'], how='left').drop(['index'], axis = 1)

# Change IP figures
df_pitchers['IP'] = df_pitchers['IP'].apply(change_IP)

In [27]:
# Apply the remove_percentages function to all percentage (string) columns
for i in ['K-BB%','CSW%','SwStr%','HardHit%','HR/FB','O-Swing%','Z-Swing%','Swing%','O-Contact%','Z-Contact%','Contact%','Zone%']:
  df_pitchers[i] = df_pitchers[i].apply(remove_percentages)

# Fill-in all pitchers who missed a year during arbitration due to injury/demotion
df_pitchers.fillna(dict.fromkeys(df_pitchers.columns[5:], 0), inplace=True)

df_pitchers

,Name,Prev. Season,Position,Service Time,Salary,G,GS,IP,BABIP,ERA,...,AVG,WHIP,HR/FB,O-Swing%,Z-Swing%,Swing%,O-Contact%,Z-Contact%,Contact%,Zone%
0,Andy Sonnanstine,2010,SP,3,912000,41.0,4.0,81.00,0.277,4.44,...,0.259,1.36,11.3,27.5,66.9,47.0,64.6,88.7,81.5,49.4
1,Anibal Sanchez,2010,SP,4,3700000,32.0,32.0,195.00,0.305,3.55,...,0.251,1.34,4.5,29.5,64.0,46.5,65.1,86.1,79.3,49.3
2,Armando Galarraga,2010,SP,2,2300000,25.0,24.0,144.33,0.261,4.49,...,0.254,1.34,8.9,28.2,67.2,45.9,71.2,91.9,84.9,45.3
3,Bill Bray,2010,RP,3,645000,35.0,0.0,28.33,0.233,4.13,...,0.196,1.09,9.3,32.9,66.7,46.9,54.9,81.1,70.4,41.7
4,Boone Logan,2010,RP,3,1200000,51.0,0.0,40.00,0.290,2.93,...,0.230,1.35,7.5,27.9,72.3,47.7,48.0,85.3,73.2,44.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,Ross Stripling,2021,RP,5,3790000,24.0,19.0,101.33,0.270,4.80,...,0.248,1.27,17.2,28.3,71.0,47.1,66.2,85.6,79.1,44.1
1086,Erick Fedde,2021,RP,3,2150000,29.0,27.0,133.33,0.313,5.47,...,0.268,1.44,18.5,28.9,67.2,44.1,67.6,87.4,79.6,39.7
1087,Tanner Rainey,2021,RP,2,860000,38.0,0.0,31.67,0.307,7.39,...,0.236,1.71,12.2,30.7,72.0,47.5,51.2,76.9,67.1,40.8
1088,Joe Ross,2021,SP,5,2400000,20.0,19.0,108.00,0.277,4.17,...,0.234,1.22,15.5,30.9,64.0,45.8,65.3,82.5,76.1,45.1
1089,Austin Voth,2021,RP,2,875000,49.0,1.0,57.33,0.313,5.34,...,0.260,1.48,16.9,32.3,72.1,48.0,64.0,84.8,76.3,39.4

In [25]:
# Merge past arbitration position players with season statistics 
df_plyrs = pd.merge(df_plyrs, fg_hit, on=['Name', 'Prev. Season'], how='left').drop(['index'], axis = 1)
df_plyrs = df_plyrs.rename(columns={"SB": "SB_run", "CS": "CS_run"})
df_plyrs = pd.merge(df_plyrs, fg_def, on=['Name', 'Prev. Season'], how='left')
df_plyrs = df_plyrs.rename(columns={"SB": "SB_def", "CS": "CS_def"})

In [29]:
# Apply the remove_percentages function to all percentage columns
for i in ['BB%','K%','O-Swing%','Z-Swing%','Swing%','O-Contact%','Z-Contact%','Contact%','SwStr%','HardHit%','Barrel%']:
  df_plyrs[i] = df_plyrs[i].apply(remove_percentages)

# Fill-in all pitchers who missed a year during arbitration due to injury/demotion
df_plyrs.fillna(dict.fromkeys(df_plyrs.columns[5:], 0), inplace=True)

df_plyrs

,Name,Prev. Season,Position,Service Time,Salary,G,PA,H,AVG,1B,...,CS_run,UBR,Inn,E,DRS,UZR,RAA,FRM,SB_def,CS_def
0,Adam Jones,2010,CF,3,3250000,149.0,621.0,165.0,0.284,116.0,...,7.0,2.8,1298.33,7.0,-6.0,-3.8,0.0,0.0,0.0,0.0
1,Alberto Callaspo,2010,3B,3,2000000,146.0,601.0,149.0,0.265,110.0,...,3.0,-2.3,1236.00,11.0,4.0,3.4,0.0,0.0,0.0,0.0
2,Alberto Gonzalez,2010,2B,2,600000,115.0,198.0,46.0,0.247,37.0,...,0.0,-1.6,393.60,5.0,7.0,7.4,0.0,0.0,0.0,0.0
3,Alex Gordon,2010,LF,3,1400000,74.0,281.0,52.0,0.215,34.0,...,5.0,-2.3,598.33,7.0,-3.0,-3.2,0.0,0.0,0.0,0.0
4,Alexi Casilla,2010,SS,3,865000,69.0,170.0,42.0,0.276,30.0,...,1.0,0.5,370.33,5.0,2.0,3.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,Danny Jansen,2021,C,3,1950000,70.0,205.0,41.0,0.223,17.0,...,0.0,-0.2,481.33,2.0,0.0,0.0,0.0,1.3,19.0,5.0
847,Josh Bell,2021,1B,5,10000000,144.0,568.0,130.0,0.261,78.0,...,0.0,-3.3,1042.67,5.0,1.0,-2.9,2.0,0.0,0.0,0.0
848,Victor Robles,2021,OF,3,1650000,107.0,369.0,64.0,0.203,40.0,...,6.0,-2.1,792.33,0.0,0.0,-0.1,2.0,0.0,0.0,0.0
849,Juan Soto,2021,LF,3,17100000,151.0,654.0,157.0,0.313,106.0,...,7.0,0.5,1226.00,6.0,4.0,2.2,4.0,0.0,0.0,0.0
850,Andrew Stevenson,2021,LF,2,850000,109.0,213.0,44.0,0.229,33.0,...,1.0,1.0,372.30,2.0,1.0,0.2,0.0,0.0,0.0,0.0

### 2023 Data (Test Set)

In [31]:
# Clean arb data for 2023 offseason
arb23 = clean_data(arb23)

/var/folders/v0/1z629k4n0fl6w18ngmy4cp100000gn/T/ipykernel_60023/2747698335.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {df.columns[0]: 'Name' ,

In [32]:
# Editing names in both Fangraphs and Cot's Dataset due to discrepancies
fg_hit['Name'] = fg_hit['Name'].replace({'Cedric Mullins II':'Cedric Mullins'})
fg_def['Name'] = fg_def["Name"].replace({'Cedric Mullins II': 'Cedric Mullins'})

arb23['Name'] = arb23['Name'].replace({'Yu-Cheng Chang': 'Yu Chang',
                                             'Rafael Oretga': 'Rafael Ortega',
                                             'LaMonte Wade': 'LaMonte Wade Jr.',
                                             'Vladimir Jr. Guerrero': 'Vladimir Guerrero Jr.',
                                             'Giovanny Urshela': 'Gio Urshela'})

In [33]:
# Split into position players and pitchers
pitch_2023 = arb23.loc[arb23['Position'].isin(['RP','SP'])].reset_index()

hit_2023 = arb23.loc[~arb23['Position'].isin(['RP','SP'])].reset_index()

In [34]:
# Merge 2023 arbitration pitchers with 2022 season statistics 
pitch_2023 = pd.merge(pitch_2023, fg_pitch, on=['Name', 'Prev. Season'], how='left').drop(['index'], axis = 1)

# Change IP figure to 1/3 for .1, 2.3 for .2
pitch_2023['IP'] = pitch_2023['IP'].apply(change_IP)

# Apply the remove_percentages function to all percentage columns
for i in ['K-BB%','CSW%','SwStr%','HardHit%','HR/FB','O-Swing%','Z-Swing%','Swing%','O-Contact%','Z-Contact%','Contact%','Zone%']:
  pitch_2023[i] = pitch_2023[i].apply(remove_percentages)

# Fill-in all pitchers who missed a year during arbitration due to injury/demotion
pitch_2023.fillna(dict.fromkeys(pitch_2023.columns[5:], 0), inplace=True)

pitch_2023

,Name,Prev. Season,Position,Service Time,Salary,G,GS,IP,BABIP,ERA,...,AVG,WHIP,HR/FB,O-Swing%,Z-Swing%,Swing%,O-Contact%,Z-Contact%,Contact%,Zone%
0,Jaime Barria,2022,RP,3,1050000,35.0,1.0,79.33,0.227,2.61,...,0.214,1.03,11.3,33.7,72.1,51.0,68.8,84.7,78.9,45.1
1,Griffin Canning,2022,RP,3,850000,0.0,0.0,0.00,0.000,0.00,...,0.000,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Shohei Ohtani,2022,SP,5,30000000,28.0,28.0,166.00,0.289,2.33,...,0.202,1.01,9.3,32.6,68.8,48.7,48.2,81.8,69.3,44.4
3,Patrick Sandoval,2022,RP,2,2750000,27.0,27.0,148.67,0.316,2.91,...,0.243,1.34,6.3,35.5,66.5,48.0,59.5,82.5,72.3,40.2
4,Zac Gallen,2022,SP,3,5600000,31.0,31.0,184.00,0.237,2.54,...,0.185,0.91,9.1,34.8,65.7,47.1,67.8,87.1,78.5,39.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Victor Arano,2022,RP,3,925000,43.0,0.0,42.00,0.344,4.50,...,0.275,1.40,13.5,41.4,64.5,49.9,59.6,85.6,71.9,36.6
136,Carl Edwards Jr.,2022,RP,5,2250000,57.0,0.0,62.00,0.259,2.76,...,0.222,1.23,12.5,34.0,68.8,47.9,64.3,87.4,77.5,39.9
137,Kyle Finnegan,2022,RP,3,2325000,66.0,0.0,66.67,0.269,3.51,...,0.220,1.14,16.4,28.8,72.2,49.4,64.2,78.9,74.4,47.5
138,Hunter Harvey,2022,RP,3,870000,38.0,0.0,39.33,0.323,2.52,...,0.228,1.14,2.3,32.2,71.1,49.5,62.7,83.3,75.8,44.5
139,Tanner Rainey,2022,RP,3,1500000,29.0,0.0,30.00,0.284,3.30,...,0.226,1.30,12.5,34.5,75.6,52.2,57.8,75.9,69.1,43.2

In [35]:
# Merge 2023 arbitration position players with 2022 season statistics 
hit_2023 = pd.merge(hit_2023, fg_hit, on=['Name', 'Prev. Season'], how='left').drop(['index'], axis = 1)
hit_2023 = hit_2023.rename(columns={"SB": "SB_run", "CS": "CS_run"})
hit_2023 = pd.merge(hit_2023, fg_def, on=['Name', 'Prev. Season'], how='left')
hit_2023 = hit_2023.rename(columns={"SB": "SB_def", "CS": "CS_def"})

# Apply the remove_percentages function to all percentage columns
for i in ['BB%','K%','O-Swing%','Z-Swing%','Swing%','O-Contact%','Z-Contact%','Contact%','SwStr%','HardHit%','Barrel%']:
  hit_2023[i] = hit_2023[i].apply(remove_percentages)

# Fill-in all pitchers who missed a year during arbitration due to injury/demotion
hit_2023.fillna(dict.fromkeys(hit_2023.columns[5:], 0), inplace=True)

hit_2023

,Name,Prev. Season,Position,Service Time,Salary,G,PA,H,AVG,1B,...,CS_run,UBR,Inn,E,DRS,UZR,RAA,FRM,SB_def,CS_def
0,Hunter Renfroe,2022,RF,5,11900000,125,522,121,0.255,68,...,1,-0.6,1044.67,4,2.0,0.1,-2.0,0.0,0.0,0.0
1,Luis Rengifo,2022,2B,3,2300000,127,511,129,0.264,86,...,2,2.3,1056.50,15,1.0,-2.0,-5.0,0.0,0.0,0.0
2,Gio Urshela,2022,3B,5,8400000,144,551,143,0.285,100,...,0,-2.5,1147.67,6,4.0,3.1,-4.0,0.0,0.0,0.0
3,Jared Walsh,2022,1B,3,2650000,118,454,91,0.215,56,...,1,-0.8,963.00,5,-2.0,0.7,0.0,0.0,0.0,0.0
4,Taylor Ward,2022,3B,2,2750000,135,564,139,0.281,92,...,3,0.3,1133.00,5,-3.0,-2.1,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Vladimir Guerrero Jr.,2022,3B,3,14500000,160,706,175,0.274,108,...,3,-3.0,1121.00,10,3.0,-3.7,-3.0,0.0,0.0,0.0
84,Danny Jansen,2022,C,4,3500000,72,248,56,0.260,31,...,0,-0.1,524.00,7,5.0,0.0,0.0,-1.4,30.0,11.0
85,Daulton Varsho,2022,C,2,3050000,151,592,125,0.235,72,...,6,2.9,1094.40,6,16.0,18.1,16.0,-1.5,12.0,6.0
86,Lane Thomas,2022,RF,3,2200000,146,548,120,0.241,75,...,4,-0.7,1124.67,2,-1.0,2.7,-3.0,0.0,0.0,0.0
87,Ildemaro Vargas,2022,SS,3,975000,63,222,55,0.263,37,...,1,1.2,516.67,5,5.0,1.8,5.0,0.0,0.0,0.0

## Recap

In [36]:
print("Training and Validation Data (2010-2022 Hitters)", df_plyrs.shape)
print("Training and Validation Data (2010-2022 Pitchers)", df_pitchers.shape)

print("")
print("Test Data (2023 Hitters)", hit_2023.shape)
print("Training and Validation Data (2023 Pitchers)", pitch_2023.shape)

Training and Validation Data (2010-2022 Hitters) (851, 44)
Training and Validation Data (2010-2022 Pitchers) (1090, 32)

Test Data (2023 Hitters) (88, 44)
Training and Validation Data (2023 Pitchers) (140, 32)

In [37]:
df_plyrs.to_csv('plyrs.csv', index=False)
df_pitchers.to_csv('pitchers.csv', index=False)

# Proposed Solution

In this section, clearly describe a solution to the problem. The solution should be applicable to the project domain and appropriate for the dataset(s) or input(s) given. Provide enough detail (e.g., algorithmic description and/or theoretical properties) to convince us that your solution is applicable. Make sure to describe how the solution will be tested.  

If you know details already, describe how (e.g., library used, function calls) you plan to implement the solution in a way that is reproducible.

If it is appropriate to the problem statement, describe a benchmark model<a name="sota"></a>[<sup>[3]</sup>](#sotanote) against which your solution will be compared.

# Evaluation Metrics

Propose at least one evaluation metric that can be used to quantify the performance of both the benchmark model and the solution model. The evaluation metric(s) you propose should be appropriate given the context of the data, the problem statement, and the intended solution. Describe how the evaluation metric(s) are derived and provide an example of their mathematical representations (if applicable). Complex evaluation metrics should be clearly defined and quantifiable (can be expressed in mathematical or logical terms).

# Preliminary results

NEW SECTION!

Please show any preliminary results you have managed to obtain.

Examples would include:
- Analyzing the suitability of a dataset or alogrithm for prediction/solving your problem 
- Performing feature selection or hand-designing features from the raw data. Describe the features available/created and/or show the code for selection/creation
- Showing the performance of a base model/hyper-parameter setting.  Solve the task with one "default" algorithm and characterize the performance level of that base model.
- Learning curves or validation curves for a particular model
- Tables/graphs showing the performance of different models/hyper-parameters

Ideas:

-  EDA for some feature selection
-  Preprocessing: Scaling depending on EDA
-  Base-model RandomForestRegressor

In [39]:
def one_hot_encode(df, column_name):
    """
    Convert a column of categorical data in a DataFrame to one-hot encoded data.

    Args:
        df (pandas.DataFrame): The DataFrame containing the column to be encoded.
        column_name (str): The name of the column to be encoded.

    Returns:
        pandas.DataFrame: The DataFrame with the one-hot encoded column.
    """
    # Extract the column to be encoded
    column = df[column_name]
    
    # Perform one-hot encoding using pandas.get_dummies()
    one_hot_encoded = pd.get_dummies(column, prefix=column_name).astype(int)
    
    # Concatenate the one-hot encoded column with the original DataFrame
    df_encoded = pd.concat([df, one_hot_encoded], axis=1)
    
    # Drop the original column from the DataFrame
    df_encoded.drop(column_name, axis=1, inplace=True)
    
    return df_encoded

In [41]:
non_numerical_columns_pitch = df_pitchers.select_dtypes(exclude='number').columns.tolist()
non_numerical_columns_pitch

['Name', 'Position', 'Service Time']

In [42]:
non_numerical_columns_players = df_plyrs.select_dtypes(exclude='number').columns.tolist()
non_numerical_columns_players

['Name', 'Position', 'Service Time']

In [44]:
pitchers_one_hot_train = one_hot_encode(df_pitchers, 'Position')
players_one_hot_train = one_hot_encode(df_plyrs, 'Position')

In [48]:
pitchers_one_hot_test = one_hot_encode(pitch_2023, 'Position')
players_one_hot_test = one_hot_encode(hit_2023, 'Position')

In [45]:
players_one_hot_train

,Name,Prev. Season,Service Time,Salary,G,PA,H,AVG,1B,2B,...,Position_1B,Position_2B,Position_3B,Position_C,Position_CF,Position_DH,Position_LF,Position_OF,Position_RF,Position_SS
0,Adam Jones,2010,3,3250000,149.0,621.0,165.0,0.284,116.0,25.0,...,0,0,0,0,1,0,0,0,0,0
1,Alberto Callaspo,2010,3,2000000,146.0,601.0,149.0,0.265,110.0,27.0,...,0,0,1,0,0,0,0,0,0,0
2,Alberto Gonzalez,2010,2,600000,115.0,198.0,46.0,0.247,37.0,8.0,...,0,1,0,0,0,0,0,0,0,0
3,Alex Gordon,2010,3,1400000,74.0,281.0,52.0,0.215,34.0,10.0,...,0,0,0,0,0,0,1,0,0,0
4,Alexi Casilla,2010,3,865000,69.0,170.0,42.0,0.276,30.0,7.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,Danny Jansen,2021,3,1950000,70.0,205.0,41.0,0.223,17.0,13.0,...,0,0,0,1,0,0,0,0,0,0
847,Josh Bell,2021,5,10000000,144.0,568.0,130.0,0.261,78.0,24.0,...,1,0,0,0,0,0,0,0,0,0
848,Victor Robles,2021,3,1650000,107.0,369.0,64.0,0.203,40.0,21.0,...,0,0,0,0,0,0,0,1,0,0
849,Juan Soto,2021,3,17100000,151.0,654.0,157.0,0.313,106.0,20.0,...,0,0,0,0,0,0,1,0,0,0
850,Andrew Stevenson,2021,2,850000,109.0,213.0,44.0,0.229,33.0,6.0,...,0,0,0,0,0,0,1,0,0,0

In [46]:
pitchers_one_hot_train

,Name,Prev. Season,Service Time,Salary,G,GS,IP,BABIP,ERA,FIP,...,HR/FB,O-Swing%,Z-Swing%,Swing%,O-Contact%,Z-Contact%,Contact%,Zone%,Position_RP,Position_SP
0,Andy Sonnanstine,2010,3,912000,41.0,4.0,81.00,0.277,4.44,4.87,...,11.3,27.5,66.9,47.0,64.6,88.7,81.5,49.4,0,1
1,Anibal Sanchez,2010,4,3700000,32.0,32.0,195.00,0.305,3.55,3.32,...,4.5,29.5,64.0,46.5,65.1,86.1,79.3,49.3,0,1
2,Armando Galarraga,2010,2,2300000,25.0,24.0,144.33,0.261,4.49,5.09,...,8.9,28.2,67.2,45.9,71.2,91.9,84.9,45.3,0,1
3,Bill Bray,2010,3,645000,35.0,0.0,28.33,0.233,4.13,3.85,...,9.3,32.9,66.7,46.9,54.9,81.1,70.4,41.7,1,0
4,Boone Logan,2010,3,1200000,51.0,0.0,40.00,0.290,2.93,3.73,...,7.5,27.9,72.3,47.7,48.0,85.3,73.2,44.5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,Ross Stripling,2021,5,3790000,24.0,19.0,101.33,0.270,4.80,5.21,...,17.2,28.3,71.0,47.1,66.2,85.6,79.1,44.1,1,0
1086,Erick Fedde,2021,3,2150000,29.0,27.0,133.33,0.313,5.47,4.66,...,18.5,28.9,67.2,44.1,67.6,87.4,79.6,39.7,1,0
1087,Tanner Rainey,2021,2,860000,38.0,0.0,31.67,0.307,7.39,5.63,...,12.2,30.7,72.0,47.5,51.2,76.9,67.1,40.8,1,0
1088,Joe Ross,2021,5,2400000,20.0,19.0,108.00,0.277,4.17,4.36,...,15.5,30.9,64.0,45.8,65.3,82.5,76.1,45.1,0,1
1089,Austin Voth,2021,2,875000,49.0,1.0,57.33,0.313,5.34,4.90,...,16.9,32.3,72.1,48.0,64.0,84.8,76.3,39.4,1,0

In [62]:
print("Training and Validation Data (2010-2022 Pitchers)", pitchers_one_hot_train.shape)
print("Training and Validation Data (2010-2022 Hitters)", players_one_hot_train.shape)

print("")
print("Test Data (2023 Pitchers)", pitchers_one_hot_test.shape)
print("Training and Validation Data (2023 Hitters)", players_one_hot_test.shape)

Training and Validation Data (2010-2022 Pitchers) (1090, 33)
Training and Validation Data (2010-2022 Hitters) (851, 53)

Test Data (2023 Pitchers) (140, 33)
Training and Validation Data (2023 Hitters) (88, 52)

In [65]:
columns_df1 = set(players_one_hot_train.columns)
columns_df2 = set(players_one_hot_test.columns)
columns_difference = list(columns_df1 - columns_df2)
columns_difference

['Position_DH']

In [53]:
from scipy.stats import zscore

def convert_to_zscores(df):
    """
    Convert values in numerical columns of a DataFrame to their respective z-scores.

    Args:
        df (pandas.DataFrame): The DataFrame to be converted.

    Returns:
        pandas.DataFrame: The DataFrame with values converted to z-scores.
    """
    # Select only numerical columns
    numerical_columns = df.select_dtypes(include='number').columns
    
    # Apply z-score transformation to numerical columns
    df[numerical_columns] = df[numerical_columns].apply(zscore)
    
    return df

In [67]:
numerical_columns_pitchers = pitchers_one_hot_train.select_dtypes(include='number').columns.drop('Prev. Season')
numerical_columns_pitchers

Index(['Salary', 'G', 'GS', 'IP', 'BABIP', 'ERA', 'FIP', 'SwStr%', 'K-BB%',
       'HR/9', 'CSW%', 'HardHit%', 'K/9', 'BB/9', 'H/9', 'HR/9.1', 'RE24',
       'SIERA', 'AVG', 'WHIP', 'HR/FB', 'O-Swing%', 'Z-Swing%', 'Swing%',
       'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%', 'Position_RP',
       'Position_SP'],
      dtype='object')

In [68]:
numerical_columns_players = players_one_hot_train.select_dtypes(include='number').columns.drop('Prev. Season')
numerical_columns_players

Index(['Salary', 'G', 'PA', 'H', 'AVG', '1B', '2B', '3B', 'HR', 'BB%', 'K%',
       'BB/K', 'BABIP', 'wOBA', 'wRAA', 'wRC', 'RE24', 'O-Swing%', 'Z-Swing%',
       'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'SwStr%', 'EV', 'LA',
       'HardHit%', 'Barrel%', 'OPS', 'SB_run', 'CS_run', 'UBR', 'Inn', 'E',
       'DRS', 'UZR', 'RAA', 'FRM', 'SB_def', 'CS_def', 'Position_1B',
       'Position_2B', 'Position_3B', 'Position_C', 'Position_CF',
       'Position_DH', 'Position_LF', 'Position_OF', 'Position_RF',
       'Position_SS'],
      dtype='object')

In [69]:
from scipy.stats import zscore

In [70]:
players_one_hot_z_train = players_one_hot_train
players_one_hot_z_train[numerical_columns_players] = players_one_hot_z_train[numerical_columns_players].apply(zscore)

pitchers_one_hot_z_train = pitchers_one_hot_train
pitchers_one_hot_z_train[numerical_columns_pitchers] = pitchers_one_hot_z_train[numerical_columns_pitchers].apply(zscore)

In [ ]:
numerical_columns_players=numerical_columns_players.drop('Position_DH')

In [75]:
players_one_hot_z_test = players_one_hot_test
players_one_hot_z_test[numerical_columns_players] = players_one_hot_z_test[numerical_columns_players].apply(zscore)

pitchers_one_hot_z_test = pitchers_one_hot_test
pitchers_one_hot_z_test[numerical_columns_pitchers] = pitchers_one_hot_z_test[numerical_columns_pitchers].apply(zscore)

In [81]:
pitchers_one_hot_z_train.to_csv('pitchers_train_final.csv', index=False)
pitchers_one_hot_z_test.to_csv('pitchers_test_final.csv', index=False)

players_one_hot_z_train.to_csv('players_train_final.csv', index=False)
players_one_hot_z_test.to_csv('players_test_final.csv', index=False)

### At this point, training and test data has been one-hot encoded and z-scored (separately)
### We now want to perform feature selection on the data to find out which features are important in predicting arbitration salary

# Ethics & Privacy

If your project has obvious potential concerns with ethics or data privacy discuss that here.  Almost every ML project put into production can have ethical implications if you use your imagination. Use your imagination.

Even if you can't come up with an obvious ethical concern that should be addressed, you should know that a large number of ML projects that go into producation have unintended consequences and ethical problems once in production. How will your team address these issues?

Consider a tool to help you address the potential issues such as https://deon.drivendata.org

# Team Expectations

Put things here that cement how you will interact/communicate as a team, how you will handle conflict and difficulty, how you will handle making decisions and setting goals/schedule, how much work you expect from each other, how you will handle deadlines, etc...
* *Team Expectation 1*
* *Team Expectation 2*
* *Team Expecation 3*
* ...

# Project Timeline Proposal

UPDATE THE PROPOSAL TIMELINE ACCORDING TO WHAT HAS ACTUALLY HAPPENED AND HOW IT HAS EFFECTED YOUR FUTURE PLANS

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/20  |  1 PM |  Brainstorm topics/questions (all)  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/26  |  10 AM |  Do background research on topic (Pelé) | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/1  | 10 AM  | Edit, finalize, and submit proposal; Search for datasets (Beckenbaur)  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/14  | 6 PM  | Import & Wrangle Data ,do some EDA (Maradonna) | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 2/23  | 12 PM  | Finalize wrangling/EDA; Begin programming for project (Cruyff) | Discuss/edit project code; Complete project |
| 3/13  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Carlos)| Discuss/edit full project |
| 3/19  | Before 11:59 PM  | NA | Turn in Final Project  |

# Footnotes
<a name="lorenznote"></a>1.[^](#lorenz): Lorenz, T. (9 Dec 2021) Birds Aren’t Real, or Are They? Inside a Gen Z Conspiracy Theory. *The New York Times*. https://www.nytimes.com/2021/12/09/technology/birds-arent-real-gen-z-misinformation.html<br> 
<a name="admonishnote"></a>2.[^](#admonish): Also refs should be important to the background, not some randomly chosen vaguely related stuff. Include a web link if possible in refs as above.<br>
<a name="sotanote"></a>3.[^](#sota): Perhaps the current state of the art solution such as you see on [Papers with code](https://paperswithcode.com/sota). Or maybe not SOTA, but rather a standard textbook/Kaggle solution to this kind of problem